### ISSUE TITLE
Resolving Git LFS Quota Issues During Project Environment Setup

### ISSUE THREAD

**Issue by jwjScorpio** [RiS3-Lab/SHiFT#1]
Hello!

When setting up the project environment, I encountered some issues. Here are the steps I followed:

bash
mkdir gcc-arm-none-eabi-10.3-2021.12-0x24000000
tar -xvf gcc-arm-none-eabi-10.3-2021.12-0x24000000.tar.xz -C ./gcc-arm-none-eabi-10.3-2021.12-0x24000000
mkdir gcc-arm-none-eabi-10.3-2021.12-0x24000000-0x10000000
tar -xvf gcc-arm-none-eabi-10.3-2021.12-0x24000000-0x10000000.tar.xz -C ./gcc-arm-none-eabi-10.3-2021.12-0x24000000-0x10000000

At this step, I was unable to extract the files. Using the `file` command, I found that both files are ASCII text. So I tried to pull these files using `git lfs pull`, but I encountered an issue with the following message:

 "batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

Therefore, I need your assistance.

Thank you!

**Comment by jwjScorpio** [comment]
It's my email:  andromeda33442022@163.com

**Comment by jwjScorpio** [comment]
<img width="829" alt="1" src="https://github.com/user-attachments/assets/1cebf6f1-2f95-4040-a188-cbdaaac5b1fb">
"Would you mind sending me the complete toolchain files?"
Thank you!

**Comment by alejoseb** [comment]
Hi please check the latest update for the tool chains it is now available to download.

**Comment by alejoseb** [comment]
Closing as it is solved
